[tool.black]
line-length = 80

[tool.poetry]
name = "pyb_utils"
version = "0.1.0"
description = ""
authors = ["Adam Heins <mail@adamheins.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
numpy = "^1.21.5"
pybullet = "^3.2.1"
liegroups = {git = "https://github.com/utiasSTARS/liegroups"}
Pillow = "^9.0.0"
matplotlib = "^3.5.1"
opencv-python = "^4.5.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
